# Generated by Django 5.1.4 on 2026-05-12 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=50, verbose_name='Telegram')),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ожидаемая ЗП, ₽')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='В чёрном списке')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки HR')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='catalog.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Начальный'), (2, 'Базовый'), (3, 'Уверенный'), (4, 'Продвинутый'), (5, 'Экспертный')], default=3, verbose_name='Уровень')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skills', to='candidates.candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_candidates', to='catalog.skill')),
            ],
            options={
                'verbose_name': 'Навык кандидата',
                'verbose_name_plural': 'Навыки кандидатов',
                'unique_together': {('candidate', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='candidates', through='candidates.CandidateSkill', to='catalog.skill', verbose_name='Навыки'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/%Y/%m/', verbose_name='Файл резюме')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Исходное имя файла')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер, байт')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное резюме')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='candidates.candidate', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='cand_email_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['phone'], name='cand_phone_idx'),
        ),
    ]
