# Generated by Django 5.1.4 on 2026-05-12 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата, ₽')),
                ('start_date', models.DateField(verbose_name='Дата выхода')),
                ('probation_months', models.PositiveSmallIntegerField(default=3, verbose_name='Испытательный срок (мес.)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Согласован'), ('sent', 'Направлен кандидату'), ('accepted', 'Принят'), ('declined', 'Отклонён'), ('expired', 'Истёк срок')], default='draft', max_length=20, verbose_name='Статус')),
                ('document', models.FileField(blank=True, null=True, upload_to='offers/%Y/%m/', verbose_name='Файл оффера (.docx)')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='pipeline.application', verbose_name='Отклик')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('full_time', 'Штат (трудовой договор)'), ('self_employed', 'Самозанятый (НПД)'), ('individual', 'ИП (ГПХ)'), ('other', 'Иное')], default='self_employed', max_length=20, verbose_name='Форма трудоустройства')),
                ('probation_end', models.DateField(verbose_name='Окончание испытательного срока')),
                ('probation_passed', models.BooleanField(blank=True, null=True, verbose_name='Испытательный срок пройден')),
                ('probation_notes', models.TextField(blank=True, verbose_name='Заметки по испытательному сроку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hire', to='offers.offer', verbose_name='Оффер')),
            ],
            options={
                'verbose_name': 'Найм',
                'verbose_name_plural': 'Наймы',
                'ordering': ['-created_at'],
            },
        ),
    ]
