# Generated by Django 5.1.4 on 2026-05-12 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название позиции')),
                ('description', models.TextField(verbose_name='Описание задач')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending_approval', 'На согласовании'), ('approved', 'Согласована'), ('rejected', 'Отклонена')], default='draft', max_length=20, verbose_name='Статус')),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ЗП мин., ₽')),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ЗП макс., ₽')),
                ('urgency', models.CharField(choices=[('low', 'Низкая'), ('normal', 'Обычная'), ('high', 'Высокая'), ('critical', 'Критическая')], default='normal', max_length=20, verbose_name='Срочность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата согласования')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Согласовал')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_requests', to='catalog.department', verbose_name='Отдел')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_requests', to='catalog.position', verbose_name='Должность')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Заявка на найм',
                'verbose_name_plural': 'Заявки на найм',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL-идентификатор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('benefits', models.TextField(blank=True, verbose_name='Условия')),
                ('min_experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Минимальный опыт, лет')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована'), ('closed', 'Закрыта'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок закрытия')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('hiring_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Нанимающий менеджер')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Рекрутёр')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.hiringrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VacancySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Используется при расчёте score (по умолчанию 1.0)', max_digits=4, verbose_name='Вес требования')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательное')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_vacancies', to='catalog.skill')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_skills', to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'Навык вакансии',
                'verbose_name_plural': 'Навыки вакансий',
                'unique_together': {('vacancy', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(related_name='vacancies', through='vacancies.VacancySkill', to='catalog.skill', verbose_name='Требуемые навыки'),
        ),
    ]
