# Generated by Django 5.1.4 on 2026-05-12 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('hh', 'hh.ru'), ('superjob', 'SuperJob'), ('avito', 'Avito')], max_length=20, verbose_name='Источник')),
                ('external_id', models.CharField(max_length=50, verbose_name='ID на внешнем источнике')),
                ('query', models.CharField(max_length=200, verbose_name='Поисковый запрос')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('raw_payload', models.JSONField(default=dict, verbose_name='Сырой ответ API')),
                ('extracted_keywords', models.JSONField(default=list, verbose_name='Извлечённые ключевые слова')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
            ],
            options={
                'verbose_name': 'Внешняя вакансия',
                'verbose_name_plural': 'Внешние вакансии',
                'ordering': ['-fetched_at'],
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='ResumeParse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True, verbose_name='Извлечённый текст')),
                ('normalized_text', models.TextField(blank=True, verbose_name='Лемматизированный текст')),
                ('years_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Извлечённый опыт работы, лет')),
                ('parser_version', models.CharField(default='1.0', max_length=20, verbose_name='Версия парсера')),
                ('parsed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата парсинга')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed', to='candidates.resume', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Результат парсинга резюме',
                'verbose_name_plural': 'Результаты парсинга резюме',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Интегральный показатель соответствия (0-100)', max_digits=5, verbose_name='Балл, %')),
                ('verdict', models.CharField(choices=[('recommended', 'Рекомендован (≥ 70 %)'), ('match', 'Подходит (50–70 %)'), ('review', 'На решение HR'), ('auto_rejected', 'Авто-отклонено (< 50 %)')], max_length=20, verbose_name='Вердикт')),
                ('matched_keywords', models.JSONField(default=list, verbose_name='Найденные ключевые слова')),
                ('missing_keywords', models.JSONField(default=list, verbose_name='Недостающие ключевые слова')),
                ('experience_match', models.BooleanField(default=False, verbose_name='Соответствие по опыту')),
                ('extracted_experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Извлечённый опыт работы')),
                ('reasons', models.TextField(blank=True, verbose_name='Описание причин')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата расчёта')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='pipeline.application', verbose_name='Отклик')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screening_matches', to='candidates.candidate', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'Скоринг резюме',
                'verbose_name_plural': 'Скоринги резюме',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['verdict'], name='match_verdict_idx')],
            },
        ),
    ]
