# Generated by Django 5.1.4 on 2026-05-12 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('catalog', '0001_initial'),
        ('vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_reason', models.CharField(blank=True, max_length=200, verbose_name='Причина отказа')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Сопроводительное письмо')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate', verbose_name='Кандидат')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='catalog.stage', verbose_name='Текущий этап')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('hr', 'HR-интервью'), ('tech', 'Техническое интервью'), ('final', 'Финальное интервью'), ('reference', 'Сбор рекомендаций')], max_length=20, verbose_name='Тип интервью')),
                ('scheduled_at', models.DateTimeField(verbose_name='Запланировано на')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='Длительность, мин.')),
                ('meeting_link', models.URLField(blank=True, verbose_name='Ссылка на встречу')),
                ('result', models.CharField(choices=[('pending', 'Не проведено'), ('passed', 'Прошёл'), ('failed', 'Не прошёл'), ('canceled', 'Отменено')], default='pending', max_length=20, verbose_name='Результат')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка (1-5)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='pipeline.application', verbose_name='Отклик')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_interviews', to=settings.AUTH_USER_MODEL, verbose_name='Интервьюер')),
            ],
            options={
                'verbose_name': 'Интервью',
                'verbose_name_plural': 'Интервью',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='StageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='pipeline.application', verbose_name='Отклик')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменено')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_records', to='catalog.stage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'История этапа',
                'verbose_name_plural': 'История этапов',
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['vacancy', 'current_stage'], name='app_vac_stage_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('candidate', 'vacancy')},
        ),
        migrations.AddIndex(
            model_name='stagehistory',
            index=models.Index(fields=['application', 'changed_at'], name='hist_app_time_idx'),
        ),
    ]
