# Generated by Django 5.1.4 on 2026-05-12 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Навык')),
                ('lemma', models.CharField(blank=True, help_text='Используется модулем скрининга. Заполняется автоматически.', max_length=100, verbose_name='Лемма (нормальная форма)')),
                ('category', models.CharField(choices=[('language', 'Язык программирования'), ('framework', 'Фреймворк'), ('database', 'СУБД'), ('tool', 'Инструмент'), ('soft', 'Soft skill'), ('domain', 'Предметная область'), ('other', 'Иное')], default='other', max_length=20, verbose_name='Категория')),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Список альтернативных написаний для поиска', verbose_name='Синонимы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Навык / ключевое слово',
                'verbose_name_plural': 'Навыки / ключевые слова',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('jobboard', 'Доска вакансий'), ('social', 'Соц. сеть / мессенджер'), ('referral', 'Реферал'), ('event', 'Мероприятие'), ('other', 'Иное')], default='jobboard', max_length=20, verbose_name='Тип')),
                ('cost_per_month', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость в месяц, ₽')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Источник найма',
                'verbose_name_plural': 'Источники найма',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_terminal', models.BooleanField(default=False, help_text='Этап завершает воронку (оффер принят / отказ / авто-отклонено)', verbose_name='Терминальный')),
                ('color', models.CharField(default='#0d6efd', help_text='Например, #0d6efd для синего', max_length=7, verbose_name='Цвет (HEX)')),
            ],
            options={
                'verbose_name': 'Этап воронки',
                'verbose_name_plural': 'Этапы воронки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.department', verbose_name='Родительское подразделение')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Должность')),
                ('grade', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Team Lead'), ('manager', 'Менеджер'), ('other', 'Иное')], default='middle', max_length=20, verbose_name='Грейд')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ЗП мин., ₽')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ЗП макс., ₽')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='positions', to='catalog.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['department', 'title'],
            },
        ),
    ]
